//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum OpalPresenceStates {
  OpalPresenceAuthRequest = -100,
  OpalUnknownPresentity = -4,
  OpalPresenceError,
  OpalPresenceForbidden,
  OpalPresenceNone,
  OpalPresenceUnchanged,
  OpalPresenceAvailable,
  OpalPresenceUnavailable
}
