/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalParamProtocol {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalParamProtocol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamProtocol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OpalParamProtocol obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalParamProtocol(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPrefix(String value) {
    OPALJNI.OpalParamProtocol_prefix_set(swigCPtr, this, value);
  }

  public String getPrefix() {
    return OPALJNI.OpalParamProtocol_prefix_get(swigCPtr, this);
  }

  public void setUserName(String value) {
    OPALJNI.OpalParamProtocol_userName_set(swigCPtr, this, value);
  }

  public String getUserName() {
    return OPALJNI.OpalParamProtocol_userName_get(swigCPtr, this);
  }

  public void setDisplayName(String value) {
    OPALJNI.OpalParamProtocol_displayName_set(swigCPtr, this, value);
  }

  public String getDisplayName() {
    return OPALJNI.OpalParamProtocol_displayName_get(swigCPtr, this);
  }

  public void setProduct(OpalProductDescription value) {
    OPALJNI.OpalParamProtocol_product_set(swigCPtr, this, OpalProductDescription.getCPtr(value), value);
  }

  public OpalProductDescription getProduct() {
    long cPtr = OPALJNI.OpalParamProtocol_product_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OpalProductDescription(cPtr, false);
  }

  public void setInterfaceAddresses(String value) {
    OPALJNI.OpalParamProtocol_interfaceAddresses_set(swigCPtr, this, value);
  }

  public String getInterfaceAddresses() {
    return OPALJNI.OpalParamProtocol_interfaceAddresses_get(swigCPtr, this);
  }

  public void setUserInputMode(OpalUserInputModes value) {
    OPALJNI.OpalParamProtocol_userInputMode_set(swigCPtr, this, value.swigValue());
  }

  public OpalUserInputModes getUserInputMode() {
    return OpalUserInputModes.swigToEnum(OPALJNI.OpalParamProtocol_userInputMode_get(swigCPtr, this));
  }

  public void setDefaultOptions(String value) {
    OPALJNI.OpalParamProtocol_defaultOptions_set(swigCPtr, this, value);
  }

  public String getDefaultOptions() {
    return OPALJNI.OpalParamProtocol_defaultOptions_get(swigCPtr, this);
  }

  public void setMediaCryptoSuites(String value) {
    OPALJNI.OpalParamProtocol_mediaCryptoSuites_set(swigCPtr, this, value);
  }

  public String getMediaCryptoSuites() {
    return OPALJNI.OpalParamProtocol_mediaCryptoSuites_get(swigCPtr, this);
  }

  public void setAllMediaCryptoSuites(String value) {
    OPALJNI.OpalParamProtocol_allMediaCryptoSuites_set(swigCPtr, this, value);
  }

  public String getAllMediaCryptoSuites() {
    return OPALJNI.OpalParamProtocol_allMediaCryptoSuites_get(swigCPtr, this);
  }

  public void setMaxSizeUDP(long value) {
    OPALJNI.OpalParamProtocol_maxSizeUDP_set(swigCPtr, this, value);
  }

  public long getMaxSizeUDP() {
    return OPALJNI.OpalParamProtocol_maxSizeUDP_get(swigCPtr, this);
  }

  public void setProtocolMessageIdentifiers(String value) {
    OPALJNI.OpalParamProtocol_protocolMessageIdentifiers_set(swigCPtr, this, value);
  }

  public String getProtocolMessageIdentifiers() {
    return OPALJNI.OpalParamProtocol_protocolMessageIdentifiers_get(swigCPtr, this);
  }

  public void setCaFiles(String value) {
    OPALJNI.OpalParamProtocol_caFiles_set(swigCPtr, this, value);
  }

  public String getCaFiles() {
    return OPALJNI.OpalParamProtocol_caFiles_get(swigCPtr, this);
  }

  public void setCertificate(String value) {
    OPALJNI.OpalParamProtocol_certificate_set(swigCPtr, this, value);
  }

  public String getCertificate() {
    return OPALJNI.OpalParamProtocol_certificate_get(swigCPtr, this);
  }

  public void setPrivateKey(String value) {
    OPALJNI.OpalParamProtocol_privateKey_set(swigCPtr, this, value);
  }

  public String getPrivateKey() {
    return OPALJNI.OpalParamProtocol_privateKey_get(swigCPtr, this);
  }

  public void setAutoCreateCertificate(long value) {
    OPALJNI.OpalParamProtocol_autoCreateCertificate_set(swigCPtr, this, value);
  }

  public long getAutoCreateCertificate() {
    return OPALJNI.OpalParamProtocol_autoCreateCertificate_get(swigCPtr, this);
  }

  public OpalParamProtocol() {
    this(OPALJNI.new_OpalParamProtocol(), true);
  }

}
