/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalParamRegistration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalParamRegistration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalParamRegistration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OpalParamRegistration obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalParamRegistration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProtocol(String value) {
    OPALJNI.OpalParamRegistration_protocol_set(swigCPtr, this, value);
  }

  public String getProtocol() {
    return OPALJNI.OpalParamRegistration_protocol_get(swigCPtr, this);
  }

  public void setIdentifier(String value) {
    OPALJNI.OpalParamRegistration_identifier_set(swigCPtr, this, value);
  }

  public String getIdentifier() {
    return OPALJNI.OpalParamRegistration_identifier_get(swigCPtr, this);
  }

  public void setHostName(String value) {
    OPALJNI.OpalParamRegistration_hostName_set(swigCPtr, this, value);
  }

  public String getHostName() {
    return OPALJNI.OpalParamRegistration_hostName_get(swigCPtr, this);
  }

  public void setAuthUserName(String value) {
    OPALJNI.OpalParamRegistration_authUserName_set(swigCPtr, this, value);
  }

  public String getAuthUserName() {
    return OPALJNI.OpalParamRegistration_authUserName_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    OPALJNI.OpalParamRegistration_password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return OPALJNI.OpalParamRegistration_password_get(swigCPtr, this);
  }

  public void setAdminEntity(String value) {
    OPALJNI.OpalParamRegistration_adminEntity_set(swigCPtr, this, value);
  }

  public String getAdminEntity() {
    return OPALJNI.OpalParamRegistration_adminEntity_get(swigCPtr, this);
  }

  public void setTimeToLive(long value) {
    OPALJNI.OpalParamRegistration_timeToLive_set(swigCPtr, this, value);
  }

  public long getTimeToLive() {
    return OPALJNI.OpalParamRegistration_timeToLive_get(swigCPtr, this);
  }

  public void setRestoreTime(long value) {
    OPALJNI.OpalParamRegistration_restoreTime_set(swigCPtr, this, value);
  }

  public long getRestoreTime() {
    return OPALJNI.OpalParamRegistration_restoreTime_get(swigCPtr, this);
  }

  public void setEventPackage(String value) {
    OPALJNI.OpalParamRegistration_eventPackage_set(swigCPtr, this, value);
  }

  public String getEventPackage() {
    return OPALJNI.OpalParamRegistration_eventPackage_get(swigCPtr, this);
  }

  public void setAttributes(String value) {
    OPALJNI.OpalParamRegistration_attributes_set(swigCPtr, this, value);
  }

  public String getAttributes() {
    return OPALJNI.OpalParamRegistration_attributes_get(swigCPtr, this);
  }

  public OpalParamRegistration() {
    this(OPALJNI.new_OpalParamRegistration(), true);
  }

}
