/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opalvoip.opal;

public class OpalProductDescription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OpalProductDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OpalProductDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OpalProductDescription obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OPALJNI.delete_OpalProductDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVendor(String value) {
    OPALJNI.OpalProductDescription_vendor_set(swigCPtr, this, value);
  }

  public String getVendor() {
    return OPALJNI.OpalProductDescription_vendor_get(swigCPtr, this);
  }

  public void setName(String value) {
    OPALJNI.OpalProductDescription_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return OPALJNI.OpalProductDescription_name_get(swigCPtr, this);
  }

  public void setVersion(String value) {
    OPALJNI.OpalProductDescription_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return OPALJNI.OpalProductDescription_version_get(swigCPtr, this);
  }

  public void setT35CountryCode(long value) {
    OPALJNI.OpalProductDescription_t35CountryCode_set(swigCPtr, this, value);
  }

  public long getT35CountryCode() {
    return OPALJNI.OpalProductDescription_t35CountryCode_get(swigCPtr, this);
  }

  public void setT35Extension(long value) {
    OPALJNI.OpalProductDescription_t35Extension_set(swigCPtr, this, value);
  }

  public long getT35Extension() {
    return OPALJNI.OpalProductDescription_t35Extension_get(swigCPtr, this);
  }

  public void setManufacturerCode(long value) {
    OPALJNI.OpalProductDescription_manufacturerCode_set(swigCPtr, this, value);
  }

  public long getManufacturerCode() {
    return OPALJNI.OpalProductDescription_manufacturerCode_get(swigCPtr, this);
  }

  public OpalProductDescription() {
    this(OPALJNI.new_OpalProductDescription(), true);
  }

}
